INSERT INTO @@FINAL_TABLE@@(
	SELECT "PRM", "SEG", "CODE_INSEE", "CODE_POSTAL", "CODE_DEPARTEMENT", "CCD", "COMMUNE", "SI"
	, "ETAT_CONTRACTUEL", "EN_SERVICE", "CONTRAT", "TYPE_OFFRE"
	, "CAT_CIENT", "CF_CIV", "CF_NOM", "CF_PRENOM", "CF_RSOCIALE"
	, "CF_AD_1", "CF_AD_2", "CF_AD_3", "CF_AD_4", "CF_AD_5", "CF_AD_6", "IC_NOM"
	, TO_DATE(DATE_DER_MES, 'yyyy-mm-dd hh24:mi:ss'), TO_DATE(DATE_DER_CHGT_FRN, 'yyyy-mm-dd hh24:mi:ss')
	, TO_DATE(DATE_DER_MODIF_FTA, 'yyyy-mm-dd hh24:mi:ss'), TO_DATE(DATE_PREM_POS_LINKY, 'yyyy-mm-dd hh24:mi:ss')
	, "CALENDRIER", "CAL_LIBELLE", "CAL_CODE_COPIE", "FTA", "NB_CADRANS", "PS", "P_RAC", "NB_FILS"
	, "COMPTEUR", "NIV_OUV_SERV", "CPT_COMMUNICANT", "CPT_TELEOPERABLE", "CPT_ACCESSIBLE"
	, "MODE_RLV", "MEDIA", "INT_REGLAGE_DJ", "CALIBRE_DJ", "PARTICULARITE", "COLOC", "BP", "F130_EC"
	, TO_DATE(DATE_EFFET, 'yyyy-mm-dd hh24:mi:ss')
	FROM @@TMP_TABLE@@
 )