--Infos affaire
SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT, nat.NAT_C_PRESTATION as PRESTATION
, nat.NAT_C_SOUS_TYPE as PRS_OPTION, frn.FRN_T_ACTEUR as FOURNISSEUR, dem.DEM_R_STATUT as STATUT
, ee.EST_T_ETAT as ETAT_EXTERNE
, ei.EST_T_ETAT as ETAT_INTERNE
, dem.DEM_D_DEMANDE as DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET
, dem.DEM_R_MEDIA_RECEPTION as MEDIA
, mai.MAI_T_REGION as REGION, mai.MAI_T_TERRITOIRE as TERRITOIRE
, dem.DEM_B_IS_SGEL as SGEL, dem.DEM_B_IS_GINKO as GINKO, PLA_MODE_REA_CODE
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
JOIN SUIVI.ETAT_STATUT ei ON dem.DEM_K_EST_INT = ei.EST_ID
JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
LEFT JOIN SUIVI.MAILLE mai ON mai.MAI_ID = dem.DEM_K_MAI
LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE
LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE ia ON dem.AFF_T_DISCO = ia.AFF_ID
LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION t_inte ON ia.INT_ID = t_inte.INT_ID
LEFT JOIN SGEL_IAP_SCH.T_OPS_PLANIFIEES ops ON t_inte.PLA_ID = ops.PLA_ID
LEFT JOIN SGEL_IAP_SCH.T_DEMANDE t_dema ON t_inte.INT_DEM_ID = t_dema.INT_DEM_ID
LEFT JOIN SGEL_IAP_SCH.T_PLANIFICATION t_plan ON t_inte.PLA_ID =  t_plan.PLA_ID
LEFT JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE t_stru ON t_pres.PRE_DEM_STR_TAR_ID = t_stru.STR_TAR_ID
LEFT JOIN SGEL_IAP_SCH.T_RECEVABILITE t_rece ON t_pres.PRE_REC_ID = t_rece.PRE_REC_ID
WHERE 1=1
AND dem.DEM_B_IS_SGEL IN ('O')
AND dem.DEM_B_IS_GINKO IN ('O')
AND dem.DEM_D_DEMANDE >= TO_DATE('30/09/2020', 'DD/MM/YYYY')
;

--Affiche la liste des fournisseurs
SELECT DISTINCT acm.ACM_T_LIB "Acteur de marché", ctr.CTR_T_NUM "Contrat GRD", acm.ACM_C_CODE "Code SGE de l'acteur de marché", acta.ACT_C_EIC "Code EIC de l'acteur de marché", tam.TAM_C_CODE
FROM CONTRAT.ASS_CTR_TAM_ACM acta
JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
JOIN CONTRAT.TYPE_ACTEUR tam ON tam.TAM_ID = acta.TAM_ID
JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_ID = acta.CTR_ID
WHERE 1=1
AND tam.TAM_C_CODE LIKE 'F%'
--AND ctr.CTR_T_NUM = 'PROTOC-501'
;

--Trouve des logins actifs par ACM_ID
SELECT DISTINCT uti.UTI_T_LOGIN FROM UTILISATEUR.UTILISATEUR uti
JOIN UTILISATEUR.ASS_PRF_UTI prf ON uti.UTI_ID = prf.UTI_ID
WHERE uti.ACM_ID = '38' --GDF : 27, EDF : 135, POWEO : 38
AND uti.UTI_B_ACTIF = 'O'
AND prf.APU_B_ACTIF = 'O'
ORDER BY uti.UTI_T_LOGIN ASC
;

--Liste prestas SGEL
SELECT DISTINCT NAT_C_TYPE as PRS, NAT_C_SOUS_TYPE as OPT
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
WHERE DEM_B_IS_SGEL = 'O'
ORDER BY NAT_C_TYPE
;

--Codes retour DISCO
SELECT * FROM DISCO.CODE_RETOUR_DISCO_4_0 cr
JOIN DISCO.PROCESSUS_DISCO prc ON cr.PRD_ID = prc.PRD_ID
JOIN DISCO.MESSAGE_RETOUR_DISCO_4_0 mrd ON mrd.CRD_ID = cr.CRD_ID
JOIN DISCO.FAISABILITE fai ON fai.FAI_ID = mrd.FAI_ID
ORDER BY cr.CRD_C_CODE_DISCO
;

--T_REFERENTIEL
SELECT * FROM SGEL_TRV_SCH.T_REFERENTIEL
WHERE REF_CODE = 'DOUBL'
;

--Ajout d'un PDL dans la table de migration
DELETE FROM TECHNIQUE.PRM_MIGRANT_GINKO;
SELECT * FROM TECHNIQUE.PRM_MIGRANT_GINKO;
INSERT INTO TECHNIQUE.PRM_MIGRANT_GINKO (PRM_ID) VALUES ('19100578720647');

--Batchs SGEL
SELECT inst.JOB_NAME, batch.START_TIME, batch.END_TIME
FROM SGEL_BATCH_SCH.BATCH_JOB_EXECUTION batch
JOIN SGEL_BATCH_SCH.BATCH_JOB_INSTANCE inst ON inst.JOB_INSTANCE_ID = batch.JOB_INSTANCE_ID
WHERE JOB_NAME LIKE '%C15%'
ORDER BY batch.START_TIME DESC
;

--Calendriers et GPM
SELECT *
FROM SGEL_SCH.T_CALENDRIER cal
JOIN SGEL_SCH.T_STRUCTURE_TEMPORELLE sTemp ON sTemp.STT_Id = cal.STT_ID
--LEFT JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_T_NUM = cal.CAL_CONTRAT_GRDF_ID
--LEFT JOIN CONTRAT.ASS_CTR_TAM_ACM acta ON ctr.CTR_ID = acta.CTR_ID
--LEFT JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
--LEFT JOIN SGEL_SCH.T_CLASSE_TEMPORELLE cTemp ON cTemp.CAL_ID = cal.CAL_ID
--LEFT JOIN SGEL_SCH.T_CALENDRIER_GPM cad_cal ON cad_cal.CAL_ID = cal.CAL_ID
--LEFT JOIN SGEL_SCH.T_GROUPE_PERIODE_MOBILE gpm ON gpm.GPM_ID = cad_cal.GPM_ID
WHERE 1=1
--AND sTemp.STT_DOM_TENS_AUT_CODE_1 = 'BTINF'
--AND cal.CAL_CODE_COPIE = 'FD000004'
--AND cal.CAL_LIBELLE = '6 cadrans'
--AND cal.CAL_LIBELLE_COMPTEUR = '     TEMPO      '
--AND cTemp.CTF_NUMERO_CADRAN = '4'
AND cal.CAL_CONTRAT_GRDF_ID = 'GRD-F006'
--AND acm.ACM_T_LIB LIKE 'ENGIE'
--AND cal.CAL_CATEGORIE = 'CAF'
--AND cal.CAL_CODE IN 'FP000281'
--AND STT_PROFILAGE_AUTORISE = '1'
ORDER BY cal.CAL_CODE
;


--CADTOCAL
SELECT * FROM SGEL_TRV_SCH.T_TRANSCODIFICATION
WHERE TRA_CODE = 'CADTOCAL'
ORDER BY 3
;