--Boucle et curseur
SET SERVEROUTPUT ON
DECLARE

CURSOR t IS
	SELECT TABLE_NAME FROM ALL_TABLES
	WHERE OWNER = 'CAPC5'
	AND TABLE_NAME = 'TMP'
	ORDER BY 1;
	
BEGIN
  FOR c IN t LOOP
    dbms_output.put_line(c.TABLE_NAME);
  END LOOP;
END;

--Exception (création table réentrant)
BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE TEST_AFF';
		EXCEPTION
			WHEN OTHERS THEN
				IF sqlcode != -0942 THEN RAISE; END IF;
	END;
	EXECUTE IMMEDIATE 'CREATE TABLE CAPC5.TEST (PRM" VARCHAR2(14 BYTE))';
	COMMIT;
END;