CL = [
    "Log file initialised (",
    "Python version:",
    "Test connect",
    "[ttry] Exception caught match expected ('Error: either gl.CNX_INFO or gl.DB have to be defined')",
    "Test - DB undefined",
    "[ttry] Exception caught match expected ('Error: database 'TEST_DB' doesn't seem to be defined. Pease check the CONF_ORACLE conf var.')",
    "Test - ENV undefined",
    "[ttry] Exception caught match expected ('Error: database 'TEST_DB' of environment 'TEST_ENV' doesn't seem to be defined. Pease check the CONF_ORACLE conf var.')",
    "Test - OK DB only",
    "Connecting to database XE (USERNAME/PWD@localhost:1521/XE)...",
    "Connected",
    "Test - OK DB + ENV",
    "Connecting to database 'XE' of environment 'LOCAL' (USERNAME/PWD@localhost:1521/XE)...",
    "Test - OK CNX_INFO (via TNS_NAMES)",
    "Connecting to database (['USERNAME', 'PWD', 'XE_TNS'])...",
    "Error: the input file * must have a header",
    "IUTD (Is Up To Date) check for DB",
    "Can't find IUTD check file",
    "Check file saved in",
    "IUTD check OK",
    "Warning: conf of DB '*' don't seem to be up to date:",
    "y (TEST_IUTD = True)",
    "The date found in the check file doesn't match the current date",
    "Error: the input file * must have a header",
    "Error: either gl.CNX_INFO or gl.DB have to be defined",
    "Error: database * doesn't seem to be defined. Pease check the CONF_ORACLE conf var.",
    "Error: database * of environment * doesn't seem to be defined. Pease check the CONF_ORACLE conf var.",
    "Make sure the first elements of the first two lines are of different lengths",
    "Subprocess terminated (upload_interrupted)",
    "Injection running detected. Recover? (y/n)",
    "y (TEST_RECOVER = True)",
    "lines written in * ms. * lines written in total.",
    "Examples of duplicates (limited to *):",
    "Executing query '01' (connection no. 2)...",
    "Query '02' executed (connection no. 3)",
    "Writing lines for query '00' (connection no. 1)...",
    "All lines written for query '01' (149 lines written, connection no. 2)",
    "TEST_RECOVER: Automatic stop (thread no. *)",
    "Range query detected. Base query:",
    "Work in progress detected. Recover? (y/n)",
    "y (TEST_RECOVER = True)",
    "Query list modified according previous work in progress. Recovering from query '*'.",
    "lines written in * ms. * lines written in total for query '*' (connection no. *)",
    "Verifying duplicates on the first column of the output file...",
    "Resetting folders...",
    "Reset over",
    "Ranges to be queried: [",
    "Connecting to database",
    "Connecting to database * of environment",
    "Creating connection no.",
    "lines written in * ms. * lines written in total for query '06'.",
    "All lines written for query '09' (150 lines written)",
    "Executing query '09'",
    "Query '12' executed",
    "All threads are done",
    "Group by on output file...",
    "Group by over",
    "Cleaning DB...",
    "DROP TABLE TEST",
    "DB cleaned",
    "[sql] upload: start",
    "[sql] upload: end (* ms)",
    "[sql] execute: start",
    "[sql] execute: end (* ms)",
    "[sql] download: start",
    "[sql] download: end (* ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[toolDup] find_dup: start",
    "[toolDup] find_dup: end",
]
