CO = [
    "Log file initialised",
    "Python version:",
    "Testing common.send_notif",
    "Testing common.mail",
    "Testing common.string.get_duration",
]

TO = [
    "Log file initialised",
    "Python version:",
    "[toolParseXML] parse_xml: start",
    "[toolParseXML] parse_xml: end (* lines written in * ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[toolSplit] split_file: start",
    "[toolSplit] split_file: end",
    "[toolDup] find_dup: start",
    "Examples of duplicates (limited to *):",
    "List of duplicates saved in ",
    "[toolDup] find_dup: end",
    "[toolFilter] filter: start",
    "lines read in * ms. * lines read in total (* lines written in output list).",
    "[toolFilter] filter: end (* ms)",
]

DQ = [
    "Log file initialised (",
    "Python version:",
    "Error: the input file * must have a header",
    "Make sure the first elements of the first two lines are of different lengths",
    "Error: files * and * don't have the same header. Input files must have the same header.",
    "Warning: 4 different lines with the same research key were identified",
    "File comparison may not work correctly. Here are your options:",
    "c (TEST_PROMPT_DK = True)",
    "List of key duplicates written in file",
    "run_dq job initialised. Input files * and * are going to be sorted and compared.",
    "lines read in * ms. * lines read in total.",
    "lines read in * ms. * lines read in total and * lines written in the output file.",
    "Maximum number of lines reached (* lines) for list no. 1, sorting...",
    "Current list sorted. Generating temporary file no. 1...",
    "Temporary file successfully generated, input file reading goes on...",
    "Filling buffer array - Iteration no. *",
    "Emptying buffer array in output file (and removing dupes)...",
    "Deleting temporary file no. 2",
    "Output file * successfully generated (* lines written, * duplicates removed).",
    "Examples of duplicates (limited to *):",
    "Input file has more than * lines. It will be splitted in * files (max file nb set to *). Continue? (y/n)",
    "y (TEST_PROMPT_SPLIT = True)",
    "Splitted file no. 1 (*) successfully generated",
    "[dq] run_dq: start",
    "[dq] sort_file: start (*)",
    "[dq] sort_file: end (* ms)",
    "[dq] compare_files: start",
    "[dq] compare_files: end (* ms)",
    "[dq] run_dq: end (* ms)",
    "[dq] file_match: start",
    "Deep comparison of '*' and '*'...",
    "[dq] file_match: end",
    "[toolSplit] split_file: start",
    "[toolSplit] split_file: end",
]

SQ = [
    "Log file initialised (",
    "Python version:",
    "Error: the input file * must have a header",
    "IUTD (Is Up To Date) check for DB",
    "Can't find IUTD check file",
    "Check file saved in",
    "IUTD check OK",
    "Warning: conf of DB * don't seem to be up to date:",
    "y (TEST_IUTD = True)",
    "The date found in the check file doesn't match the current date",
    "Error: the input file * must have a header",
    "Make sure the first elements of the first two lines are of different lengths",
    "Automatic stop (upload_interrupted)",
    "Injection running detected. Restart? (y/n)",
    "y (TEST_RESTART = True)",
    "* lines written in * ms. * lines written in total.",
    "Examples of duplicates (limited to *):",
    "Executing query for range 01 (connection no. 2)...",
    "Query executed for range 02 (connection no. 3)",
    "Writing lines for range 00 (connection no. 1)...",
    "All lines written for range 01 (* lines written, connection no. 2)",
    "TEST_RESTART: Automatic stop (thread no. *)",
    "Range query detected. Base query:",
    "Work in progress detected. Kill? (y/n)",
    "n (TEST_RESTART = True)",
    "Range list modified",
    "lines written in * ms. * lines written in total for range * (connection no. *)",
    "Verifying duplicates on the first column of the output file...",
    "Resetting folders...",
    "Reset over",
    "Ranges to be queried: [",
    "Creating connections for DB '*' of '*' environnement (*)",
    "lines written in * ms. * lines written in total for range 06.",
    "All lines written for range 09 (* lines written)",
    "Executing query for range 09",
    "Query executed for range 12",
    "All threads are done",
    "Group by on output file...",
    "Group by over",
    "[sql] upload: start",
    "[sql] upload: end (* ms)",
    "[sql] execute: start",
    "[sql] execute: end (* ms)",
    "[sql] download: start",
    "[sql] download: end (* ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[toolDup] find_dup: start",
    "[toolDup] find_dup: end",
]

RL = [
    "Log file initialised",
    "Python version:",
    "Error: right array is void",
    "Error: query must contain @@IN@@",
    "Executing queries (thread no. 1)",
    "Error: the input file * must have a header",
    "Make sure the first elements of the first two lines are of different lengths",
    "queries executed in * ms. * queries executed in total (thread no. 1).",
    "All queries executed for thread no. * (* lines written)",
    "TEST_RESTART: Automatic stop (thread no. *)",
    "Work in progress detected. Kill? (y/n)",
    "n (TEST_RESTART = True)",
    "Restarting from query no. * for thread no. *",
    "Thread no. * had finished its run",
    "Building groups of elements...",
    "List of elements prepared, it contains * elements",
    "Group list built: * elements to be processed distributed in * groups (* max per group)",
    "The * groups will be processed in parallel on * different connection pools (max * groups per thread).",
    "Executing queries (thread no. 1)...",
    "End of thread no. 1",
    "All threads are done",
    "Checking duplicates on the first column of the output file...",
    "Examples of duplicates (limited to *):",
    "[reqlist] left_join_files: start",
    "[reqlist] left_join_files: end (* ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[sql] upload: start",
    "[sql] upload: end (*)",
    "[sql] execute: start",
    "[sql] execute: end (*)",
    "[reqlist] run_reqList: start",
    "[reqlist] run_reqList: end (*)",
    "[reqlist] download: start",
    "[reqlist] download: end (* lines written in * ms)",
    "[toolDup] find_dup: start",
    "[toolDup] find_dup: end",
]
