BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE @@TABLE_NAME@@';
		EXCEPTION
			WHEN OTHERS THEN
				IF sqlcode != -0942 THEN RAISE; END IF;
	END;
	EXECUTE IMMEDIATE 'CREATE TABLE "CAPC5"."@@TABLE_NAME@@" 
   (	"PRM" VARCHAR2(14 BYTE), 
	"SEG" VARCHAR2(5 BYTE), 
	"CODE_INSEE" VARCHAR2(5 BYTE), 
	"CODE_POSTAL" VARCHAR2(5 BYTE), 
	"CODE_DEPARTEMENT" VARCHAR2(2 BYTE), 
	"CCD" VARCHAR2(3 BYTE), 
	"COMMUNE" VARCHAR2(32 BYTE), 
	"SI" VARCHAR2(5 BYTE), 
	"ETAT_CONTRACTUEL" VARCHAR2(6 BYTE), 
	"EN_SERVICE" VARCHAR2(1 BYTE), 
	"CONTRAT" VARCHAR2(26 BYTE), 
	"TYPE_OFFRE" VARCHAR2(2 BYTE), 
	"CAT_CIENT" VARCHAR2(4 BYTE), 
	"CF_CIV" VARCHAR2(3 BYTE), 
	"CF_NOM" VARCHAR2(50 CHAR), 
	"CF_PRENOM" VARCHAR2(38 CHAR), 
	"CF_RSOCIALE" VARCHAR2(128 CHAR), 
	"CF_AD_1" VARCHAR2(38 CHAR), 
	"CF_AD_2" VARCHAR2(38 CHAR), 
	"CF_AD_3" VARCHAR2(38 CHAR), 
	"CF_AD_4" VARCHAR2(38 CHAR), 
	"CF_AD_5" VARCHAR2(38 CHAR), 
	"CF_AD_6" VARCHAR2(38 CHAR), 
	"IC_NOM" VARCHAR2(50 CHAR), 
	"DATE_DER_MES" VARCHAR2(20 BYTE), 
	"DATE_DER_CHGT_FRN" VARCHAR2(20 BYTE), 
	"DATE_DER_MODIF_FTA" VARCHAR2(20 BYTE), 
	"DATE_PREM_POS_LINKY" VARCHAR2(20 BYTE), 
	"CALENDRIER" VARCHAR2(26 BYTE), 
	"CAL_LIBELLE" VARCHAR2(26 BYTE), 
	"FTA" VARCHAR2(26 BYTE), 
	"NB_CADRANS" VARCHAR2(2 BYTE), 
	"CAL_CODE_COPIE" VARCHAR2(26 BYTE), 
	"PS" VARCHAR2(4 BYTE), 
	"P_RAC" VARCHAR2(5 BYTE), 
	"COMPTEUR" VARCHAR2(6 BYTE), 
	"NIV_OUV_SERV" VARCHAR2(1 BYTE), 
	"CPT_COMMUNICANT" VARCHAR2(1 BYTE), 
	"CPT_TELEOPERABLE" VARCHAR2(1 BYTE), 
	"CPT_ACCESSIBLE" VARCHAR2(1 BYTE), 
	"MODE_RLV" VARCHAR2(4 BYTE), 
	"MEDIA" VARCHAR2(3 BYTE), 
	"INT_REGLAGE_DJ" VARCHAR2(5 BYTE), 
	"CALIBRE_DJ" VARCHAR2(5 BYTE), 
	"PARTICULARITE" VARCHAR2(5 BYTE), 
	"COLOC" VARCHAR2(1 BYTE), 
	"BP" VARCHAR2(1 BYTE), 
	"F130_EC" VARCHAR2(8 BYTE), 
	"DATE_EFFET" VARCHAR2(20 BYTE), 
	"NB_FILS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAPC5_DATA"';
	COMMIT;
END;