SELECT DISTINCT POINT, TYPE_SRV_ADAM, PERIO_TR_ADAM, ETAT_ADAM, DATE_DEBUT_ADAM, TYPE_MESURE_ADAM, PAS_MESURE_ADAM, TYPE_DEMANDEUR_ADAM, DEMANDEUR_ADAM
FROM
(
	SELECT seg.PRM_ID POINT
	, seg.SEGMENT
	, srv.SERVICE_ID, srv.SERVICE_TYPE as TYPE_SRV_ADAM, srv.PERIODICITE_TRANSMISSION PERIO_TR_ADAM
	, srv.ETAT_CODE ETAT_ADAM, srv.DATE_DEBUT DATE_DEBUT_ADAM, srv.DATE_FIN
	, mes.TYPE_CODE as TYPE_MESURE_ADAM, mes.PAS as PAS_MESURE_ADAM
	, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
			WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
			WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
			WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
			ELSE 'Indéterminé'
			END "TYPE_DEMANDEUR_ADAM"
	, CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
			WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
			END "DEMANDEUR_ADAM"
	, DENSE_RANK() OVER (PARTITION BY seg.PRM_ID ORDER BY srv.ETAT_CODE, mes.PAS, srv.SERVICE_TYPE DESC, srv.DATE_DEBUT DESC, srv.PERIODICITE_TRANSMISSION, ben.CODE) RANG
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
	AND srv.ETAT_CODE IN ('ACTIF', 'DEMANDE')
	AND mes.TYPE_CODE = 'CDC'
	AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
	--AND seg.PRM_ID = '04322141735602'
	--AND seg.PRM_ID IN ('50092131995305', '01100144558519', '01100144564042', '50090976744268')
	AND seg.PRM_ID IN @@IN@@
)
WHERE RANG  = 1