SELECT POINT, ETAT_ADAM, DEBUT_ADAM, FIN_ADAM FROM
(
	SELECT seg.PRM_ID POINT, srv.ETAT_CODE ETAT_ADAM, srv.DATE_DEBUT DEBUT_ADAM, srv.DATE_FIN FIN_ADAM
	, DENSE_RANK() OVER (PARTITION BY seg.PRM_ID ORDER BY srv.DATE_DEBUT DESC, srv.DATE_MODIFICATION DESC) as RANG
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	WHERE 1=1	
	AND SERVICE_TYPE = 'OPPENR'
	AND srv.ETAT_CODE NOT IN ('TERMINE', 'SUPPRIME')
	AND seg.SEGMENT = 'C5'
	AND seg.PRM_ID IN @@IN@@
)
WHERE RANG = '1'