SELECT POINT, LIBELLE_GKO, DEBUT_GKO, FIN_GKO, FIN_PREVUE_GKO, DEMANDEUR, PORTAIL, PUBLICATION, SI_DEMANDEUR FROM
(
SELECT pds.REFERENCE POINT, srv.LIBELLECOURT LIBELLE_GKO, srvs.DATEDEBUTPREVUE DEBUT_GKO, srvs.DATEFIN FIN_GKO, srvs.DATEFINPREVUE FIN_PREVUE_GKO
   , DECODE (srvs.TYPEDEMANDEUR,
       0, 'Fournisseur',
       1, 'Fournisseur Tiers',
       2, 'Client',
       3, 'Interne',
       4, 'Tiers autorisé',
       srvs.TYPEDEMANDEUR
      ) DEMANDEUR,
   CASE WHEN srvs.TYPEDEMANDEUR = 2 THEN DECODE (nvl(act1.EMAIL,''),'','NON','OUI') ELSE DECODE (nvl(act2.EMAIL,''),'','NON','OUI') END PORTAIL,
   DECODE (substr(srv.libellecourt,6),
       'JO', 'Journalière',
       'ME', 'Mensuelle',
       'XX'
      ) PUBLICATION,
   CASE WHEN srvs.TYPEDEMANDEUR = 3 THEN act1.NOM END SI_DEMANDEUR
, DENSE_RANK() OVER (PARTITION BY pds.REFERENCE ORDER BY srvs.DATEDEBUTPREVUE DESC) as RANG
FROM GAHFLD.TSERVICESOUSCRIT srvs,
   GAHFLD.TPOINTDESERVICE pds,
   GAHFLD.TSERVICE srv,
   GAHFLD.TACTEUR act1,
   GAHFLD.TACTEUR act2,
   GAHFLD.TCONTRAT ctr,
   GAHFLD.TPOINTACCESSERVICESCLIENT pdsclient,
   GAHFLD.TROLEACTEUR rolact,
   GAHFLD.TMODELEROLEACTEUR modrolact
WHERE srvs.TYPEDEMANDEUR IS NOT NULL
   AND srvs.POINTDESERVICE_ID = pds.ID
   AND srvs.SERVICE_ID = srv.ID
   AND ctr.POINTACCESSERVICESCLIENT_ID = pdsclient.ID
   AND pdsclient.POINTDESERVICE_ID = pds.ID
   AND rolact.OBJETMAITRE_ID = ctr.ID
   AND act2.ID = rolact.ACTEUR_ID
   AND ctr.STATUTEXTRAIT = 1
   AND rolact.MODELEROLEACTEUR_ID = modrolact.ID
   AND modrolact.LIBELLE = 'titulaire contrat de fourniture'
   AND srv.LIBELLECOURT LIKE 'CDC%'
   AND srvs.DEMANDEUR_ID = act1.id (+)
   --AND ctr.DATEFIN IS NULL
   --AND srvs.DATEFIN IS NULL
   AND pds.REFERENCE IN @@IN@@
)
WHERE RANG = 1