SELECT prm.PRM_ID POINT
, cf.PRS_PHY_CIVILITE CF_CIV, cf.PRS_PHY_NOM CF_NOM, cf.PRS_PHY_PRENOM CF_PRENOM, cf.PRS_COORD_EMAIL CF_EMAIL, cf.PRS_COORD_TELEPHONE_FIXE CF_TEL_FIX, cf.PRS_COORD_TELEPHONE_PORT CF_TEL_PORT
, ic.PRS_PHY_CIVILITE IC_CIV, ic.PRS_PHY_NOM IC_NOM, ic.PRS_PHY_PRENOM IC_PRENOM, ic.PRS_COORD_EMAIL IC_EMAIL, ic.PRS_COORD_TELEPHONE_FIXE IC_TEL_FIX, ic.PRS_COORD_TELEPHONE_PORT IC_TEL_PORT
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
JOIN SGEL_PRM_SCH.T_PERSONNE cf ON situ.SCN_CLIENT_FINAL_ID = cf.PRS_ID
JOIN SGEL_PRM_SCH.T_PERSONNE ic ON situ.SCN_CLIENT_FINAL_ID = ic.PRS_ID
WHERE 1=1
AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
AND prm.PRM_SC_SEGMENT = 'C5'
AND prm.PRM_DG_ETAT_CODE = 'ACTI'
AND prm.PRM_ID IN @@IN@@