SELECT POINT, AFF_EN_COURS_SGE FROM
(
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFF_EN_COURS_SGE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND dem.DEM_B_IS_SGEL IN ('O')
	AND dem.DEM_B_IS_GINKO IN ('O')
	AND nat.NAT_C_PRESTATION IN ('F100B', 'F120B', 'F130B', 'F140', 'F180')
	AND dem.DEM_R_STATUT IN ('AFF-ENCOURS')
	AND dem.DEM_ID_PRM IN @@IN@@
)
WHERE RANG = '1'