--Analyse abos / désabos
SELECT COUNT(*) VOL, TYPE_DEMANDEUR, DEMANDEUR, TYPE_SERVICE, TYPE_MESURE, PAS_MESURE, PERIODICITE_TRANSMISSION, DATE_DEBUT
FROM
(
	SELECT seg.PRM_ID POINT
	, srv.SERVICE_ID, srv.SERVICE_TYPE as TYPE_SERVICE, srv.PERIODICITE_TRANSMISSION
	, mes.TYPE_CODE as TYPE_MESURE, mes.PAS as PAS_MESURE
	, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
			WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
			WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
			WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
			ELSE 'Indéterminé'
			END "TYPE_DEMANDEUR"
	, CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
			WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
			END "DEMANDEUR"
	, TRUNC(srv.DATE_FIN) DATE_FIN
	, TRUNC(srv.DATE_DEBUT) DATE_DEBUT
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
--	AND srv.ETAT_CODE = 'ACTIF'
	AND seg.SEGMENT = 'C5'
	AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
)
WHERE 1=1
AND TYPE_DEMANDEUR = 'Fournisseur'
AND DATE_FIN = TO_DATE('25/09/2020', 'DD/MM/YYYY')
--AND DATE_FIN >= TO_DATE('24/09/2020', 'DD/MM/YYYY')
--AND DATE_FIN <= TO_DATE('28/09/2020', 'DD/MM/YYYY')
AND DEMANDEUR = 'EDF'
AND TYPE_SERVICE = 'TRANSREC'
GROUP BY TYPE_DEMANDEUR, DEMANDEUR, TYPE_SERVICE, TYPE_MESURE, PAS_MESURE, PERIODICITE_TRANSMISSION, DATE_DEBUT
ORDER BY 1 DESC

--Volumétries globales (détail demandeur)
SELECT TYPE_DEMANDEUR, DEMANDEUR, TYPE_SERVICE, TYPE_MESURE, PAS_MESURE, PERIODICITE_TRANSMISSION, COUNT(1) as VOLUMETRIE
FROM
(
	SELECT seg.PRM_ID POINT
	, srv.SERVICE_ID, srv.SERVICE_TYPE as TYPE_SERVICE, srv.PERIODICITE_TRANSMISSION
	, mes.TYPE_CODE as TYPE_MESURE, mes.PAS as PAS_MESURE
	, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
			WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
			WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
			WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
			ELSE 'Indéterminé'
			END "TYPE_DEMANDEUR"
	, CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
			WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
			END "DEMANDEUR"
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
	AND srv.ETAT_CODE = 'ACTIF'
	AND seg.SEGMENT = 'C5'
	AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
)
GROUP BY TYPE_DEMANDEUR, DEMANDEUR, TYPE_SERVICE, TYPE_MESURE, PAS_MESURE, PERIODICITE_TRANSMISSION
ORDER BY 1, 2, 3
;

--Infos srv
SELECT POINT, SERVICE_ID, DATE_DEBUT, ETAT, DEMANDEUR, TYPE_SERVICE, TYPE_MESURE, PAS_MESURE, PERIODICITE_TRANSMISSION
FROM
(
    SELECT seg.PRM_ID POINT
	, srv.SERVICE_ID, srv.SERVICE_TYPE as TYPE_SERVICE, srv.PERIODICITE_TRANSMISSION
	, srv.ETAT_CODE ETAT, srv.DATE_DEBUT
	, mes.TYPE_CODE as TYPE_MESURE, mes.PAS as PAS_MESURE
    , CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
            WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
            WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
            WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
            ELSE 'Indéterminé'
            END "TYPE_DEMANDEUR"
    , CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
            WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
            END "DEMANDEUR"
    FROM ADA_SCH.SERVICE_SOUSCRIT srv
    LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
    LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
    LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
    WHERE 1=1
    AND srv.ETAT_CODE IN ('ACTIF', 'DEMANDE')
    AND seg.SEGMENT = 'C5'
    AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
	AND srv.DATE_DEBUT > '01/11/2019'
)
WHERE DEMANDEUR = 'EVELER'

--Service souscrit + affaires  + interventions
SELECT srv.SERVICE_ID, srv.ETAT_CODE, seg.PRM_ID, srv.SERVICE_TYPE as TYPE_SRV, srv.PERIODICITE_TRANSMISSION as PERIO, mes.TYPE_CODE as TYPE_M, mes.PAS as PAS
, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'Client'
		WHEN ben.TYPE = 'FINALITE' THEN 'Interne'
		WHEN ben.TYPE = 'CONTRAT' AND (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Fournisseur'
		WHEN ben.TYPE = 'CONTRAT' AND NOT (ben.code LIKE 'GRD-F%' or ben.code = 'PROTOC-501') THEN 'Tiers'
		ELSE 'Indéterminé'
		END "TYPE_DEMANDEUR"
, CASE  WHEN ben.TYPE = 'FINALITE' THEN ben.CODE
		WHEN ben.TYPE = 'CONTRAT' THEN ben.LIBELLE
		END "DEMANDEUR"
,  srv.DATE_DEBUT, srv.DATE_FIN, srv.DATE_CREATION,srv.DATE_MODIFICATION
, aff.AFFAIRE_ID, aff.INITIATEUR_LOGIN, aff.STATUT_CODE as STATUT_AFF
, int.*
FROM ADA_SCH.SERVICE_SOUSCRIT srv
LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
LEFT JOIN AFFAIRE_SERVICE_SOUSCRIT aff_srv ON srv.SERVICE_ID = aff_srv.SERVICE_ID
LEFT JOIN ADA_SCH.AFFAIRE aff ON aff_srv.AFFAIRE_ID = aff.AFFAIRE_ID
LEFT JOIN ADA_SCH.INTERVENTION int ON srv.SERVICE_ID = int.SERVICE_ID
WHERE 1=1
--AND srv.ETAT_CODE = 'ACTIF'
AND seg.SEGMENT = 'C5'
--AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
AND seg.PRM_ID = '25869609237775'
;

--Suivi activations temporaires
SELECT COUNT(1) as VOLUMETRIE, ETAT_CODE, DATE_DEBUT, DATE_FIN 
FROM ADA_SCH.SERVICE_SOUSCRIT srv
WHERE srv.finalite_code = 'PANELRESEAU'
AND DATE_DEBUT >= TO_DATE('26/04/2019', 'dd/mm/yyyy')
AND DATE_DEBUT <= TO_DATE('03/05/2019', 'dd/mm/yyyy')
GROUP BY ETAT_CODE, DATE_DEBUT, DATE_FIN
ORDER BY 3
;

--Prestations
SELECT COUNT(*), prs.CODE
FROM ADA_SCH.AFFAIRE aff
JOIN ADA_SCH.AFFAIRE_PRESTATION prs ON aff.PRESTATION_ID = prs.ID
WHERE 1=1
AND DATE_CREATION >= TO_DATE('23/09/2019', 'DD/MM/YYYY')
AND DATE_CREATION < TO_DATE('24/09/2019', 'DD/MM/YYYY')
AND aff.STATUT_CODE NOT IN ('ANNULEE')
GROUP BY prs.CODE
ORDER BY 1 DESC
;

--Oppositions
SELECT seg.PRM_ID as POINT, srv.SERVICE_ID, srv.ETAT_CODE, srv.DATE_DEBUT, srv.DATE_FIN, srv.MOTIF_FIN_LIBELLE
FROM ADA_SCH.SERVICE_SOUSCRIT srv
LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
WHERE 1=1
AND SERVICE_TYPE = 'OPPENR'
AND srv.ETAT_CODE NOT IN ('TERMINE', 'SUPPRIME')
AND seg.SEGMENT = 'C5'