--Jointure PRM - Situations contractuelles
SELECT prm.PRM_ID
DECODE(situ.SCN_APP_APPLICATION_CODE, 'QETGC', 'DISCO', situ.SCN_APP_APPLICATION_CODE) as SI
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
WHERE 1=1
AND prm.PRM_DG_ETAT_CODE = 'ACTI'
AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
AND prm.PRM_SC_SEGMENT = 'C5'
AND prm.PRM_DG_APP_INSTANCE_SI IN ('0321', '0322', '0323', '0324', '0325', '0326', '0327', '0328')
AND situ.SCN_APP_APPLICATION_CODE IN ('GINKO', 'QETGC')
AND prm.PRM_ID = '01143560041889'
;

--Fournisseurs
WITH CTR_FRN AS (
    SELECT DISTINCT ctr.CTR_T_NUM CONTRAT, acm.ACM_T_LIB FOURNISSEUR
    FROM CONTRAT.ASS_CTR_TAM_ACM acta
    JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
    JOIN CONTRAT.TYPE_ACTEUR tam ON tam.TAM_ID = acta.TAM_ID
    JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_ID = acta.CTR_ID
    WHERE 1=1
    AND tam.TAM_C_CODE LIKE 'F%'
    )

SELECT prm.PRM_ID, cf.FOURNISSEUR
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
JOIN CTR_FRN cf ON situ.SCN_CF_NUMERO_CONTRAT = cf.CONTRAT

--Jointure PRM - Situations contractuelles - Client final - Interlocuteur client
SELECT prm.PRM_ID POINT
, cf.PRS_PHY_CIVILITE CF_CIV, cf.PRS_PHY_NOM CF_NOM, cf.PRS_PHY_PRENOM CF_PRENOM, cf.PRS_COORD_EMAIL CF_EMAIL, cf.PRS_COORD_TELEPHONE_FIXE CF_TEL_FIX, cf.PRS_COORD_TELEPHONE_PORT CF_TEL_PORT, cf.PRS_MOR_NUMERO_SIRET SIRET
, ic.PRS_PHY_CIVILITE IC_CIV, ic.PRS_PHY_NOM IC_NOM, ic.PRS_PHY_PRENOM IC_PRENOM, ic.PRS_COORD_EMAIL IC_EMAIL, ic.PRS_COORD_TELEPHONE_FIXE IC_TEL_FIX, ic.PRS_COORD_TELEPHONE_PORT IC_TEL_PORT
FROM SGEL_PRM_SCH.T_PRM prm
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
JOIN SGEL_PRM_SCH.T_PERSONNE cf ON situ.SCN_CLIENT_FINAL_ID = cf.PRS_ID
JOIN SGEL_PRM_SCH.T_PERSONNE ic ON situ.SCN_INTERLOCUTEUR_CLIENT_ID = ic.PRS_ID
WHERE 1=1
AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
AND prm.PRM_SC_SEGMENT = 'C5'
AND prm.PRM_DG_ETAT_CODE = 'ACTI'
AND prm.PRM_ID = '01143560041889'
;

--Afficher les caractéristiques d'un PDL
SELECT DISTINCT
prm.PRM_ID as PDL
, prm.PRM_SC_ETAT_CONTRACTUEL_CODE as SCN
, prm.PRM_DG_NUMERO_CONTRAT as CONTRAT
, prm.PRM_SC_SEGMENT as SEGMENT
, situ.SCN_APP_APPLICATION_CODE as SI
, situ.SCN_ST_TYPE_OFFRE_CODE "TYPE OFFRE"
, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA
, situ.SCN_ST_CONTEXTE_UTIL_CODE as CTX
, situ.SCN_CF_CATEGORIE_CODE as CAT
, situ.SCN_CF_INDICATEUR_MHRV as MHRV
, situ.SCN_ST_CODE_TARIF_ACH_DISCO as TARIF
, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS
, DECODE(scm.SCM_DC_STRUCTURE_COMPTAGE_CODE,
	'AMM', 'LINKY',
	scm.SCM_DC_STRUCTURE_COMPTAGE_CODE) as COMPTEUR
, prm.PRM_DG_NIV_OUV_SERV as NIV_OUV_SRV
, CASE WHEN prm.PRM_DG_NIV_OUV_SERV > 0 THEN 'O' ELSE 'N' END COMMUNIQUANT
, alim.SAL_ETAT_ALIM_CODE as SAL
, talim.ALI_PUISS_RACCO_SOUTI_V as P_RAC
, eqeCPT.EQE_MC_NB_CADRANS as NB_CADRANS, eqeCPT.EQE_CP_NB_FILS as NB_FILS
, eqeCPT.EQE_NUM_SERIE as IDC
, eqeDJ.EQE_DJ_INT_REGLAGE_V as PDJ, eqeDJ.EQE_DJ_CALIBRE_CODE as CDJ
, prm.PRM_DG_COMMENTAIRE as FLAG, prm.PRM_TECH_DATE_MAJ
, prm.PRM_AIN_LIGNE2 as LIGNE2, prm.PRM_AIN_LIGNE3 as LIGNE3, prm.PRM_AIN_LIGNE4 as LIGNE4, prm.PRM_AIN_LIGNE5 as LIGNE5, prm.PRM_AIN_LIGNE6 as LIGNE6
FROM SGEL_PRM_SCH.T_PRM prm
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_ALIMENTATION alim ON prm.SAL_ID = alim.SAL_ID
LEFT JOIN SGEL_PRM_SCH.T_ALIMENTATION talim ON talim.ALI_ID = alim.ALI_PRINCIPALE_ID
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeCPT ON eqeCPT.SCM_C_ID = prm.SCM_ID
LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeDJ ON eqeDJ.EQE_ID = scm.EQE_DISJONCTEUR_ID
WHERE 1=1
--AND prm.PRM_ID = '07528075206878'
AND prm.PRM_ID IN ('22234876949527', '22565412341065', '22452677208285', '21178002857066', '22118813260640', '21247177850967', '21241823422616', '21230680057978', '21573371796674', '22579305248513')
--AND prm.PRM_ID LIKE '191%'
--AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
--AND situ.SCN_APP_APPLICATION_CODE = 'GINKO'
--AND situ.SCN_SITU_TYPE = 'C'
--AND prm.PRM_SC_SEGMENT = 'C5'
--AND situ.SCN_SIT_DATE_FIN IS NULL
--AND situ.SCN_CF_NUMERO_CONTRAT = 'GRD-F006'
--AND situ.SCN_SIT_ETAT_CODE = 'actif' !champ de mauvaise qualité! non fiable
--AND alim.SAL_ETAT_ALIM_CODE = 'ALIM'
;

---Nombre de PDL GINKO par contrat---------------------------------------------
SELECT COUNT(*), prm.PRM_DG_NUMERO_CONTRAT
FROM SGEL_PRM_SCH.T_PRM prm 
JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
JOIN SGEL_PRM_SCH.T_SITUATION_ALIMENTATION alim ON prm.SAL_ID = alim.SAL_ID
WHERE 1=1
AND situ.SCN_APP_APPLICATION_CODE = 'GINKO' GROUP BY prm.PRM_DG_NUMERO_CONTRAT
ORDER BY 1 DESC
;

--Nombre de PDL par SI, code centre et applictions (DISCO/GINKO)
SELECT DISTINCT COUNT(PDL), CENTRE, INST, APP FROM(
  SELECT prm.PRM_ID as PDL, SUBSTR(prm.PRM_ID, 1,3) as CENTRE, situ.SCN_APP_INSTANCE_SI as INST, situ.SCN_APP_APPLICATION_CODE as APP
  FROM SGEL_PRM_SCH.T_PRM prm 
  JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
  WHERE 1=1
  AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
  AND situ.SCN_APP_APPLICATION_CODE IN ('GINKO', 'QETGC')
  AND situ.SCN_SITU_TYPE = 'C'
  AND situ.SCN_SIT_DATE_FIN IS NULL
)
GROUP BY CENTRE, INST, APP
ORDER BY 1 DESC
;

--Compteurs LINKY
SELECT COUNT(*), SI FROM(
SELECT DISTINCT prm.PRM_ID as PDL, situ.SCN_APP_APPLICATION_CODE as SI
FROM SGEL_PRM_SCH.T_PRM prm
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_COMPTAGE scm ON scm.SCM_ID = prm.SCM_ID
WHERE 1=1
AND scm.SCM_DC_STRUCTURE_COMPTAGE_CODE = 'AMM'
)
GROUP BY SI
;

--Groupes période mobile
SELECT COUNT(1), GPM FROM
(
	SELECT DISTINCT situ.SCN_APP_REF_POINT as POINT, situ.SCN_ST_GRP_PERIODE_MOBILE_CODE as GPM
	FROM SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ
	WHERE SCN_ST_GRP_PERIODE_MOBILE_CODE IS NOT NULL
	AND situ.SCN_SITU_TYPE = 'C'
)
GROUP BY GPM
ORDER BY 1 DESC
;

106400	G0000005
66820	G0000004
65857	G0000001
26971	G0000003
18240	G0000002
8107	G0007445
116	G0000019
10	G0000047

--Situations contractuelles actives par FTA (04/06/2019)
SELECT *
FROM SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ
WHERE 1=1
AND situ.SCN_APP_APPLICATION_CODE IN ('GINKO')
AND situ.SCN_SITU_TYPE = 'C'
AND situ.SCN_SIT_DATE_FIN IS NULL
--AND situ.SCN_SIT_ETAT_CODE = 'actif' !champ de mauvaise qualité!
;

7487681	BTINFCUST
4310748	BTINFMU4
3648667	BTINFMUDT
1429689	BTINFCU4
170432	BTINFLU
100	
2	BTINFCUDT
1	BTINFMUST

--Situations contractuelles actives par fournisseur
WITH CTR_FRN AS (
    SELECT DISTINCT ctr.CTR_T_NUM CONTRAT, acm.ACM_T_LIB FOURNISSEUR
    FROM CONTRAT.ASS_CTR_TAM_ACM acta
    JOIN CONTRAT.ACTEUR_MARCHE acm ON acm.ACM_ID = acta.ACM_ID
    JOIN CONTRAT.TYPE_ACTEUR tam ON tam.TAM_ID = acta.TAM_ID
    JOIN CONTRAT.CONTRAT ctr ON ctr.CTR_ID = acta.CTR_ID
    WHERE 1=1
    AND tam.TAM_C_CODE LIKE 'F%'
    )

SELECT VOLUMETRIE, vol.CONTRAT, FOURNISSEUR FROM (
    SELECT COUNT(1) as VOLUMETRIE, CONTRAT FROM
    (
        SELECT DISTINCT situ.SCN_APP_REF_POINT, situ.SCN_CF_NUMERO_CONTRAT as CONTRAT
        FROM SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ
        WHERE 1=1
        AND situ.SCN_APP_APPLICATION_CODE IN ('GINKO')
        AND situ.SCN_SITU_TYPE = 'C'
        AND situ.SCN_SIT_DATE_FIN IS NULL
    )
    GROUP BY CONTRAT
) vol
JOIN CTR_FRN cf ON vol.CONTRAT = cf.CONTRAT
ORDER BY 1 DESC
;

--Compteurs marché d'affaire
SELECT COUNT(1), EQE_ME_TYPE_APPAREIL, PRM_SC_SEGMENT FROM SGEL_PRM_SCH.T_PRM prm
LEFT JOIN SGEL_PRM_SCH.T_EQUIPEMENT eqeCPT ON eqeCPT.SCM_C_ID = prm.SCM_ID
WHERE 1=1
AND prm.PRM_SC_SEGMENT <> 'C5'
AND prm.PRM_SC_SEGMENT <> 'INDET'
GROUP BY EQE_ME_TYPE_APPAREIL, PRM_SC_SEGMENT
ORDER BY 1 DESC
;

--QDD champs
SELECT COUNT(*) as NB_POINTS, PRM_ETAT, PRM_ETAT_CTR, SITU_ETAT_CTR, SITU_ETAT_CTR_DATE, SEG
FROM
(
    SELECT 
    prm.PRM_ID, prm.PRM_DG_ETAT_CODE as PRM_ETAT
    , situ.SCN_SIT_ETAT_CODE as SITU_ETAT_CTR
    , prm.PRM_SC_ETAT_CONTRACTUEL_CODE as PRM_ETAT_CTR
    , CASE
        WHEN situ.SCN_SIT_DATE_FIN IS NULL THEN 'SERVC'
        WHEN situ.SCN_SIT_DATE_FIN IS NOT NULL THEN 'RESIL'
        END as SITU_ETAT_CTR_DATE
    , prm.PRM_SC_SEGMENT as SEG
    FROM SGEL_PRM_SCH.T_PRM prm
    JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
)
GROUP BY PRM_ETAT, PRM_ETAT_CTR, SITU_ETAT_CTR, SITU_ETAT_CTR_DATE, SEG
;
