--Points et segments
SELECT * 
FROM BIC_REFERENTIEL.T_ROLE_TITULAIRE rot
JOIN BIC_REFERENTIEL.T_CONTRAT_ACCES ctr ON ctr.ROT_ID = rot.ROT_ID
-- JOIN BIC_REFERENTIEL.T_PERSONNE prs ON rot.PER_ID = prs.PER_ID
WHERE 1=1
AND (ctr.ACC_SEGMENT IN ('INDET', 'C2-C4', 'C2-C4 (OH)') OR ctr.ACC_SEGMENT IS NULL)
;

--Count sur les segments
SELECT COUNT(*), ACC_SEGMENT
FROM BIC_REFERENTIEL.T_CONTRAT_ACCES
GROUP BY ACC_SEGMENT
ORDER BY 1 DESC
;

--QDD segments
SELECT rot.PRM_ID as POINT, ctr.ACC_SEGMENT as SEG
FROM BIC_REFERENTIEL.T_ROLE_TITULAIRE rot
JOIN BIC_REFERENTIEL.T_CONTRAT_ACCES ctr ON ctr.ROT_ID = rot.ROT_ID
WHERE 1=1
AND ctr.ACC_DATE_FIN IS NULL