CL = [
    "Log file initialised",
    "Python version:",
    "Error: right array is void",
    "Error: query must contain @@IN@@",
    "Executing query '01' (connection no. 1)...",
    "Query '01' executed (connection no. 1)",
    "Writing lines for query '01'...",
    "All lines written for query '01' (0 lines written, connection no. 1)",
    "Merging and deleting * temporary files...",
    "Data fetched from * (2 900 lines written)",
    "Error: the input file * must have a header",
    "Make sure the first elements of the first two lines are of different lengths",
    "TEST_RECOVER: Automatic stop (thread no. *)",
    "Work in progress detected. Recover? (y/n)",
    "y (TEST_RECOVER = True)",
    "Query list modified according previous work in progress. Recovering from query '*'.",
    "Building query list to be input in sql.dowload...",
    "Query list built: 2 894 elements to be processed distributed in 15 groups (200 max per group). They will be processed in parallel by 3 connection pools.",
    "All threads are done",
    "Checking duplicates on the first column of the output file...",
    "Examples of duplicates (limited to *):",
    "Cleaning DB...",
    "DROP TABLE TEST",
    "DB cleaned",
    "[rl] left_join_files: start",
    "[rl] left_join_files: end (* ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[sql] upload: start",
    "[sql] upload: end (*)",
    "[sql] execute: start",
    "[sql] execute: end (*)",
    "[rl] reqlist: start",
    "[rl] reqlist: end (*)",
    "[sql] download: start",
    "[sql] download: end (* ms)",
    "[toolDup] find_dup: start",
    "[toolDup] find_dup: end",
]
