SELECT seg.PRM_ID POINT
, srv.ETAT_CODE ETAT_ADAM
, srv.SERVICE_ID ID
, srv.DATE_DEBUT
, srv.DATE_FIN
--, DENSE_RANK() OVER (PARTITION BY seg.PRM_ID ORDER BY srv.SERVICE_TYPE DESC, srv.ETAT_CODE, srv.DATE_DEBUT DESC, srv.SERVICE_ID DESC) as RANG
FROM ADA_SCH.SERVICE_SOUSCRIT srv
LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
WHERE 1=1
AND srv.ETAT_CODE IN ('ACTIF', 'DEMANDE')
AND seg.SEGMENT = 'C5'
AND mes.TYPE_CODE = 'IDX'
AND seg.PRM_ID IN @@IN@@