SELECT pds.REFERENCE as POINT
, act.NOM as FOURNISSEUR
, pds.DATEPROCHAINERELEVEREELLE 
FROM GAHFLD.TESPACEDELIVRAISON edl
   JOIN GAHFLD.TPOINTDESERVICE pds ON edl.ID = pds.ESPACEDELIVRAISON_ID
   JOIN GAHFLD.CONTRAT_ESPACESDELIVRAISON ce ON edl.ID = ce.DEST
   JOIN GAHFLD.TCONTRAT ctr ON ce.SOURCE = ctr.ID
   LEFT JOIN GAHFLD.TROLE rol ON ctr.TITULAIRE_ID = rol.ID
   LEFT JOIN GAHFLD.TACTEUR act ON rol.ACTEUR_ID = act.ID
   LEFT JOIN GAHFLD.TOFFREPRODUIT op ON ctr.OFFREPRODUIT_ID = op.ID
WHERE 1=1
   AND ctr.DATEFIN IS NULL
   AND pds.REFERENCE IN @@IN@@