SELECT pds.REFERENCE as POINT
, TO_CHAR(pds.DATEMODIFICATION, 'DD/MM/YYYY') DATE_MODIF_GKO
FROM GAHFLD.TPOINTDESERVICE pds
WHERE 1=1
AND pds.ETAT <> '5'
AND pds.DATESUPPRESSION IS NULL
AND pds.REFERENCE IN @@IN@@