SELECT 
  pds.REFERENCE POINT
, SUBSTR(dt.LIBELLE, 20) AS DR
FROM GAHFLD.TPOINTDESERVICE pds
JOIN GAHFLD.EDL_DECOUPAGETERRITOIRE edldt ON edldt.SOURCE = pds.ESPACEDELIVRAISON_ID
JOIN GAHFLD.TDECOUPAGETERRITOIRE dt ON (dt.ID = edldt.DEST AND dt.TYPEDECOUPAGETERRITOIRE = '3')
WHERE pds.REFERENCE IN @@IN@@