SELECT DISTINCT
prm.PRM_ID as POINT
, prm.PRM_DG_ETAT_CODE as ETAT_SGE
, prm.PRM_SC_ETAT_CONTRACTUEL_CODE as SCN_SGE
, situ.SCN_APP_APPLICATION_CODE as SI_SGE
FROM SGEL_PRM_SCH.T_PRM prm
LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
WHERE 1=1
AND prm.PRM_ID IN @@IN@@