WITH t as(
	SELECT prm.PRM_ID as PRM
	, situ.SCN_GF_CALENDRIER_FOURN_CODE as CALENDRIER
	, situ.SCN_ST_FORM_TARIF_ACHEMIN as FTA
	, situ.SCN_ST_P_SOUSCRITE_MAX_V as PS
	FROM SGEL_PRM_SCH.T_PRM prm
	LEFT JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
	LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
)

, aff as (
	SELECT dem.DEM_ID_PRM as PRM, dem.AFF_T_DISCO as AFFAIRE, nat.NAT_C_PRESTATION PRESTATION
	, dem.DEM_R_STATUT STATUT
	, dem.DEM_D_DEMANDE DATE_DEMANDE
	, t_rece.PRE_REC_REC_DATE_EFFET as DATE_EFFET_PREVUE
	, t_pres.PRE_DEM_DATEEFFET DATE_EFFET_SOUHAITEE
	, DECODE(dem.DEM_B_IS_GINKO, 'O', 'GINKO', 'N', 'COSY') SI
	, frn.FRN_T_ACTEUR as FOURNISSEUR, ee.EST_T_ETAT as ETAT_EXTERNE
	, dem.DEM_T_REF_DEMANDE REF_DEMANDEUR, dem.DEM_T_REGROUPEMENT REF_REGROUPEMENT
	, dem.DEM_T_INITIATEUR UTI_LOGIN, uti.UTI_R_CIVILITE UTI_CIV, uti.UTI_T_NOM UTI_NOM, uti.UTI_T_PRENOM UTI_PRENOM
	, t_pres.PRE_DEM_SC_TYPEOFFRE TYPE_OFFRE, t_stru.STR_TAR_ST_FORTARACH FTA_CIBLE
	, t_stru.STR_TAR_ST_PUISMAXVAL PS_CIBLE, t_stru.STR_TAR_ST_GFRN_CAL_CODE CAL_CIBLE
	, t_rece.PRE_REC_REC_MODEREA_CODE MODEREA, t_dema.INT_DEM_DATE DATE_INTER_SOUHAITEE, t_plan.PLA_DATE DATE_INTER_PREVUE
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC, t_stru.STR_TAR_ST_FORTARACH) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
	LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
	LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE
	LEFT JOIN SGEL_IAP_SCH.T_RECEVABILITE t_rece ON t_pres.PRE_REC_ID = t_rece.PRE_REC_ID
	LEFT JOIN SGEL_IAP_SCH.T_STRUCTURE_TARIFAIRE t_stru ON t_pres.PRE_DEM_STR_TAR_ID = t_stru.STR_TAR_ID
	LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE ia ON dem.AFF_T_DISCO = ia.AFF_ID
	LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION t_inte ON ia.INT_ID = t_inte.INT_ID
	LEFT JOIN SGEL_IAP_SCH.T_PLANIFICATION t_plan ON t_inte.PLA_ID =  t_plan.PLA_ID
	LEFT JOIN SGEL_IAP_SCH.T_DEMANDE t_dema ON t_inte.INT_DEM_ID = t_dema.INT_DEM_ID
	LEFT JOIN UTILISATEUR.UTILISATEUR uti ON dem.DEM_K_UTI_INITIATEUR = uti.UTI_ID
	WHERE 1=1
	AND (
			nat.NAT_C_PRESTATION IN ('F120A', 'F120B', 'F130A', 'F130B', 'F140', 'F140A'
									,'F180', 'F200B', 'F185O4', 'F360', 'F420C', 'F800B', 'F920', 'F940B')
		OR
			t_pres.PRE_FICHEOPTION_CODE = 'F185O4'
		)
	AND dem.DEM_R_STATUT IN ('AFF-ENCOURS', 'AFF-TERMINEE')
	AND dem.DEM_D_EFFET >= TO_DATE('01/09/2020', 'DD/MM/YYYY')
)

, cal as (
	SELECT cal.CAL_CODE, cal.CAL_CODE_COPIE
	FROM SGEL_SCH.T_CALENDRIER cal
)

SELECT aff.PRM, aff.AFFAIRE, aff.SI, aff.PRESTATION, aff.STATUT, aff.ETAT_EXTERNE, aff.FOURNISSEUR, aff.TYPE_OFFRE
, aff.DATE_DEMANDE, aff.DATE_EFFET_SOUHAITEE, aff.DATE_EFFET_PREVUE, aff.DATE_INTER_SOUHAITEE, aff.DATE_INTER_PREVUE
, aff.MODEREA
, aff.REF_DEMANDEUR, aff.REF_REGROUPEMENT, aff.UTI_CIV, aff.UTI_NOM, aff.UTI_PRENOM, aff.UTI_LOGIN
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.PS ELSE NULL END PS_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.PS_CIBLE ELSE NULL END PS_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.FTA ELSE NULL END FTA_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.FTA_CIBLE ELSE NULL END FTA_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN t.CALENDRIER ELSE NULL END CAL_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN aff.CAL_CIBLE ELSE NULL END CAL_CIBLE
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN calc_init.CAL_CODE_COPIE ELSE NULL END CAL_COPIE_INIT
, CASE WHEN aff.STATUT = 'AFF-ENCOURS' AND aff.PRESTATION IN ('F130A', 'F130B') THEN calc_cible.CAL_CODE_COPIE ELSE NULL END CAL_COPIE_CIBLE
, CASE WHEN aff.STATUT = 'AFF-TERMINEE' OR aff.PRESTATION NOT IN ('F130A', 'F130B') OR aff.SI = 'DISCO' THEN NULL
		WHEN t.FTA = aff.FTA_CIBLE AND t.PS = aff.PS_CIBLE AND calc_init.CAL_CODE_COPIE = calc_cible.CAL_CODE_COPIE THEN 'O'
		ELSE 'N' END F130_EC_ISO
FROM aff
JOIN t ON aff.PRM = t.PRM
LEFT JOIN cal calc_init ON t.CALENDRIER = calc_init.CAL_CODE
LEFT JOIN cal calc_cible ON aff.CAL_CIBLE = calc_cible.CAL_CODE
WHERE 1=1
AND aff.RANG = 1
AND t.PRM IN @@IN@@
-- AND t.PRM IN ('01273516633705', '01268162040512', '01270477513693', '01273371826499', '01404196735262', '02157018695650', '01220260430745')
-- AND aff.AFFAIRE = 'A056WY9E'
;