SELECT POINT, AFFAIRE, DATE_DEMANDE, DATE_EFFET
FROM(
	SELECT DISTINCT dem.DEM_ID_PRM as POINT, dem.AFF_T_DISCO as AFFAIRE
	, dem.DEM_D_DEMANDE DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET
	, DENSE_RANK() OVER (PARTITION BY dem.DEM_ID_PRM ORDER BY dem.DEM_D_DEMANDE DESC) as RANG
	FROM SUIVI.DEMANDE dem
	JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
	WHERE 1=1
	AND nat.NAT_C_PRESTATION LIKE ('F130%')
	AND dem.DEM_ID_PRM IN @@IN@@
)
WHERE RANG = 1