WITH t as (
	SELECT 
	seg.PRM_ID PRM
	, srv.SERVICE_ID
	, CASE  WHEN ben.TYPE = 'PERSONNE' THEN 'x' ELSE '' END CLIENT
	, CASE  WHEN ben.TYPE <> 'PERSONNE' THEN 'x' ELSE '' END AUTRE
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.BENEFICIAIRE ben ON srv.BENEFICIAIRE_ID = ben.ID
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
	AND srv.ETAT_CODE = 'ACTIF'
	AND seg.SEGMENT = 'C5'
	AND mes.TYPE_CODE = 'CDC'
	AND srv.SERVICE_TYPE IN ('TRANSREC', 'CCDC')
	--AND DATE_DEBUT >= TO_DATE('28/09/2020', 'DD/MM/YYYY')
--	AND seg.PRM_ID IN ('01201157712813', '01206367490040', '01224746689043', '01289001414730')
	ORDER BY 1
)

SELECT COUNT(*) VOL, DEMANDEURS FROM
(
	SELECT DISTINCT PRM
	, CASE WHEN CLIENT = 'x' AND AUTRE = 'x' THEN 'CLIENT ET AUTRE'
		 WHEN CLIENT = 'x' AND AUTRE IS NULL THEN 'CLIENT SEUL'
		 WHEN CLIENT IS NULL THEN 'AUTRE SANS CLIENT'
		 END DEMANDEURS
	FROM
	(
		SELECT PRM, MAX(CLIENT) CLIENT, MAX(AUTRE) AUTRE
		FROM t
		GROUP BY PRM
	)
)
GROUP BY DEMANDEURS
