SELECT sge.PRM, sge.CODE_INSEE, sge.CODE_DEPARTEMENT, sge.CCD, sge.COMMUNE, sge.DR, sge.REG
, sge.SI, sge.EN_SERVICE, sge.TYPE_OFFRE, sge.CALENDRIER, sge.CAL_LIBELLE CAL_LIBELLE_COMPTEUR
, sge.PS PS_MAX_KW, sge.P_RAC P_RAC_KW, sge.COMPTEUR, sge.CPT_COMMUNICANT, sge.CPT_ACCESSIBLE
, sge.MODE_RLV, sge.MEDIA, sge.F130_EC, sge.DATE_EFFET, sge.BP, sge.COLOC
FROM SGE sge
WHERE 1=1
AND SI IN ('DISCO', 'GINKO')
AND EN_SERVICE ='O'
AND TYPE_OFFRE ='OH'
AND DR = '@@RG_DR@@'