SELECT COMPTEUR, TYPE_CAL, COUNT(*) VOL FROM
(
	SELECT 
	CASE WHEN COMPTEUR = 'LINKY' AND CPT_COMMUNICANT = 'O' THEN 'LINKY COM'
		ELSE 'CPT NON COM' END COMPTEUR
	, DECODE(CALENDRIER, 'FC000049', 'EJP', 'FC000050', 'TEMPO', 'AUTRE') TYPE_CAL
	FROM SGE
	WHERE 1=1
	AND SI IN ('DISCO', 'GINKO')
	AND EN_SERVICE ='O'
	AND TYPE_OFFRE ='OH'
)
GROUP BY COMPTEUR, TYPE_CAL
ORDER BY 1