SELECT seg.PRM_ID POINT, srv.SERVICE_ID, srv.DATE_FIN
FROM ADA_SCH.SERVICE_SOUSCRIT srv
LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
WHERE 1=1
AND srv.ETAT_CODE = 'ACTIF'
AND seg.SEGMENT = 'C5'
AND srv.DATE_FIN < SYSDATE - 1