SELECT prm.PRM_ID as POINT
, CASE WHEN prm.PRM_DG_ETAT_CODE = 'ACTI' AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC' THEN '1' ELSE '0' END as ETAT
FROM SGEL_PRM_SCH.T_PRM prm
WHERE 1=1
AND prm.PRM_SC_SEGMENT = 'C5'