-- points actifs avec contrat SCN et contrat calendrier incohérent
SELECT * FROM
(
	SELECT prm.PRM_ID as POINT, situ.SCN_GF_CALENDRIER_FOURN_CODE as CAL_SGE
		, DECODE(prm.PRM_DG_NUMERO_CONTRAT
			, 'PROTOC-501', 'GRD-F003'
			, prm.PRM_DG_NUMERO_CONTRAT) CTR_SCN_SGE
		, cal.CAL_CONTRAT_GRDF_ID CTR_CAL_SGE
	FROM SGEL_PRM_SCH.T_PRM prm
		JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
		LEFT JOIN SGEL_SCH.T_CALENDRIER cal ON situ.SCN_GF_CALENDRIER_FOURN_CODE = cal.CAL_CODE
	WHERE 1=1
		AND situ.SCN_APP_APPLICATION_CODE = 'GINKO'
		AND situ.SCN_SEGMENT ='C5'
		AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
		--AND prm.PRM_ID = '23572503617778'
)
WHERE (CTR_SCN_SGE <> CTR_CAL_SGE) OR CAL_SGE IS NULL