WITH a AS
(
SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT
, ee.EST_T_ETAT as ETAT
, dem.DEM_D_DEMANDE as DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET, dem.DEM_D_CLOTURE DATE_CLOTURE
, dem.DEM_B_IS_GINKO as GINKO
, DECODE(dem.DEM_K_CATEGORIE, '1', 'PRO', '2', 'PART') CAT_CLIENT
, t_rece.PRE_REC_REC_MODEREA_CODE MODE_REA
, TO_CHAR(t_plan.PLA_DATE, 'DD/MM/YYYY') DATE_INTERVENTION
, TO_CHAR(t_pres.PRE_DEM_DATEEFFET, 'DD/MM/YYYY') DATE_EFFET_SOUHAITEE
, DECODE(t_pres.PRE_DEM_C5_RESIL_PROC_ACC, '0', 'N', '1', 'O') PROC_ACC
, DECODE(t_pres.PRE_DEM_AD_MANQUEMENT_OBL_CTR, '0', 'N', '1', 'O') MANQUEMENT_OBL_CTR
, DECODE(t_pres.PRE_DEM_AD_NON_RECONDUC_CTR, '0', 'N', '1', 'O') NON_RECONDUC_CTR
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
JOIN SUIVI.FOURNISSEUR frn ON frn.FRN_ID = dem.DEM_K_FRN
LEFT JOIN SGEL_IAP_SCH.T_AFFAIRE aff ON dem.AFF_T_DISCO = aff.AFF_ID
LEFT JOIN SGEL_IAP_SCH.T_PRESTATION t_pres ON aff.AFF_ID_SEQUENCE = t_pres.AFF_ID_SEQUENCE
LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION_AFFAIRE ia ON dem.AFF_T_DISCO = ia.AFF_ID
LEFT JOIN SGEL_IAP_SCH.T_INTERVENTION t_inte ON ia.INT_ID = t_inte.INT_ID
LEFT JOIN SGEL_IAP_SCH.T_PLANIFICATION t_plan ON t_inte.PLA_ID =  t_plan.PLA_ID
LEFT JOIN SGEL_IAP_SCH.T_RECEVABILITE t_rece ON t_pres.PRE_REC_ID = t_rece.PRE_REC_ID
WHERE 1=1
AND dem.DEM_B_IS_GINKO = 'O'
AND nat.NAT_C_PRESTATION = 'F140'
AND PRE_FICHEOPTION_CODE = 'F140BO2'
AND dem.DEM_D_DEMANDE >= TO_DATE('01/01/2019', 'DD/MM/YYYY')
AND dem.DEM_D_DEMANDE <= TO_DATE('01/01/2020', 'DD/MM/YYYY')
--AND dem.AFF_T_DISCO = 'A04N95MR'
)

, b as
(
SELECT DISTINCT dem.AFF_T_DISCO as AFFAIRE, dem.DEM_ID_PRM as POINT
, ee.EST_T_ETAT as ETAT
, dem.DEM_D_DEMANDE as DATE_DEMANDE, dem.DEM_D_EFFET as DATE_EFFET, dem.DEM_D_CLOTURE DATE_CLOTURE
, dem.DEM_B_IS_GINKO as GINKO
, DECODE(dem.DEM_K_CATEGORIE, '1', 'PRO', '2', 'PART') CAT_CLIENT
, DECODE(MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'B_TELE_INTERVENTION'
	) THEN info.VAR_T_DATA END), 'N', 'SITE', 'O', 'DIST') as MODE_REA
, MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'D_RDV_PROPOSE'
	) THEN info.VAR_T_DATA END) as DATE_INTERVENTION
, MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'D_EFFET_SOUHAITEE'
	) THEN info.VAR_T_DATA END) as DATE_EFFET_SOUHAITEE
, MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'B_PROCEDURE_COURTE'
	) THEN info.VAR_T_DATA END) as PROC_ACC
, MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'B_MANQUE_OBLIGATION'
	) THEN info.VAR_T_DATA END) as MANQUEMENT_OBL_CTR
, MAX(CASE WHEN info.VAR_ID = (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE
	WHERE VAR_C_CODE = 'B_NON_REC_CONTRAT'
	) THEN info.VAR_T_DATA END) as NON_RECONDUC_CTR
FROM SUIVI.DEMANDE dem
JOIN SUIVI.NATURE nat ON dem.DEM_K_NAT = nat.NAT_ID
LEFT JOIN SUIVI.ETAT_STATUT ee ON dem.DEM_K_EST_EXT = ee.EST_ID
JOIN AFFAIRE.INFO_VARIABLE info ON info.AFF_ID = dem.DEM_ID
WHERE 1=1
AND dem.DEM_B_IS_GINKO = 'N'
AND nat.NAT_C_PRESTATION = 'F140'
AND nat.NAT_C_SOUS_TYPE = 'F140B3'
AND dem.DEM_D_DEMANDE >= TO_DATE('01/01/2019', 'DD/MM/YYYY')
AND dem.DEM_D_DEMANDE <= TO_DATE('01/01/2020', 'DD/MM/YYYY')
--AND dem.AFF_T_DISCO IN ('A04NJ7KT', 'A03Z744F')
AND info.VAR_ID IN (
	SELECT VAR_ID FROM AFFAIRE.VARIABLE WHERE VAR_C_CODE IN (
	'B_MANQUE_OBLIGATION'
	, 'B_NON_REC_CONTRAT'
	, 'B_PROCEDURE_COURTE'
	, 'B_TELE_INTERVENTION'
	, 'D_RDV_PROPOSE'
	, 'D_EFFET_SOUHAITEE'
	)
)
GROUP BY dem.AFF_T_DISCO, dem.DEM_ID_PRM
, ee.EST_T_ETAT
, dem.DEM_D_DEMANDE, dem.DEM_D_EFFET, dem.DEM_D_CLOTURE
, dem.DEM_B_IS_GINKO
, DECODE(dem.DEM_K_CATEGORIE, '1', 'PRO', '2', 'PART')
)

SELECT
AFFAIRE, POINT, GINKO, ETAT, CAT_CLIENT
, CASE WHEN MODE_REA IS NULL THEN
	CASE WHEN DATE_INTERVENTION IS NULL THEN 'SANS' ELSE 'SITE' END
	ELSE MODE_REA END MODE_REA
, DATE_DEMANDE, DATE_EFFET, DATE_EFFET_SOUHAITEE, DATE_CLOTURE, DATE_INTERVENTION
, PROC_ACC, MANQUEMENT_OBL_CTR, NON_RECONDUC_CTR
FROM
(
SELECT * FROM a
UNION
SELECT * FROM b
)
--WHERE AFFAIRE IN ('A03Z744F', 'A03Z745I')
