SELECT prm.PRM_ID POINT
	, DECODE(situ.SCN_ST_FORM_TARIF_ACHEMIN,
		'BTINFCUST', 'CUST',	
		'BTINFMUDT', 'MUDT',
		'BTINFLU', 'LU',
		'BTINFCU4', 'CU4',
		'BTINFMU4', 'MU4')as FTA
	, situ.SCN_ST_CONTEXTE_UTIL_CODE as CTX
FROM SGEL_PRM_SCH.T_PRM prm
	JOIN SGEL_PRM_SCH.T_SITUATION_CONTRACTUELLE situ ON prm.SCN_ID = situ.SCN_ID
WHERE 1=1
	AND prm.PRM_DG_ETAT_CODE = 'ACTI'
	AND prm.PRM_SC_ETAT_CONTRACTUEL_CODE = 'SERVC'
	AND prm.PRM_SC_SEGMENT = 'C5'
	AND prm.PRM_DG_APP_INSTANCE_SI IN ('0321', '0322', '0323', '0324', '0325', '0326', '0327', '0328')
	--AND situ.SCN_ST_FORM_TARIF_ACHEMIN = 'BTINFLU'
	--AND prm.PRM_Id = '22569030328002'
	AND prm.PRM_ID LIKE '211%'