CO = [
    "Log file initialised",
    "Python version:",
    "_init.txt)",
    "ParTools package successfully initialised",
    "Checkout the README.md on GitHub",
    "Get started here",
    "Set up your conf here",
    "Test of like functions",
    "like simple ok",
    "like m ok",
    "like_list ok",
    "like_dict ok",
    "Test msg_box",
    "Message box notification successfully sent",
    "Test string.get_duration",
]
