BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE @@TABLE_NAME@@';
		EXCEPTION
			WHEN OTHERS THEN
				IF sqlcode != -0942 THEN RAISE; END IF;
	END;
	EXECUTE IMMEDIATE 'CREATE TABLE @@TABLE_NAME@@ (
		"D_UPDATE" DATE
	)';
	COMMIT;
END;
