BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE TEST_IUTD';
		EXCEPTION
			WHEN OTHERS THEN
				IF sqlcode != -0942 THEN RAISE; END IF;
	END;
	EXECUTE IMMEDIATE 'CREATE TABLE TEST_IUTD (
		"D_UPDATE" DATE
	)';
	COMMIT;
END;
