INSERT INTO @@TABLE_NAME@@ (
PRM, AFFAIRE, SI, PRESTATION, STATUT, ETAT_EXTERNE, FOURNISSEUR, TYPE_OFFRE
, DATE_DEMANDE
, DATE_EFFET_SOUHAITEE
, DATE_EFFET_PREVUE
, DATE_INTER_SOUHAITEE
, DATE_INTER_PREVUE
, MODEREA
, REF_DEMANDEUR, REF_REGROUPEMENT, UTI_CIV, UTI_NOM
, UTI_PRENOM, UTI_LOGIN, PS_INIT, PS_CIBLE, FTA_INIT, FTA_CIBLE
, CAL_INIT, CAL_CIBLE, CAL_COPIE_INIT, CAL_COPIE_CIBLE, F130_EC_ISO
)
VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10
, :11, :12, :13, :14, :15, :16, :17, :18, :19, :20
, :21, :22, :23, :24, :25, :26, :27, :28, :29
)
