CL = [
    "Log file initialised",
    "Python version:",
    "[toolParseXML] parse_xml: start",
    "lines processed in * ms. * lines processed in total.",
    "Parse dictionary generated (82 lines processed)",
    "2 lines written in * ms. 2 lines written in total.",
    "[toolParseXML] parse_xml: end (3 lines written in * ms)",
    "[dq] file_match: start",
    "[dq] file_match: end",
    "[toolSplit] split_file: start",
    "[toolSplit] split_file: end",
    "[toolDup] find_dup: start",
    "Examples of duplicates (limited to *):",
    "List of duplicates saved in ",
    "[toolDup] find_dup: end",
    "[toolFilter] filter: start",
    "lines read in * ms. * lines read in total (* lines written in output list).",
    "[toolFilter] filter: end (* ms)",
    "[toolShuf] shuffle_file: start",
    "[toolShuf] shuffle_file: end",
    "[toolBF] read_big_file: start",
    "EOF reached. 2 901 lines read.",
    "A05IANDR;290078031;07394934787868",
    "e (TEST = True)",
    "[toolBF] read_big_file: end",
    "[toolBF] search_big_file: start",
    "Searching string '22173227102607' in file *...",
    "String found in line no. 45 of list no. 19 (global line no. 1 845) in col 20!",
    "Current list written in *",
    "[toolBF] search_big_file: end (* ms)",
    "[dq] sort_file: start (*)",
    "Generating first list to be sorted...",
    "Output file * successfully generated (2 897 lines written, 4 pure duplicates removed).",
    "4 key duplicates found. List written in *",
    "[dq] sort_file: end (* ms)",
]
