CL = [
    "Log file initialised (",
    "Python version:",
    "Error: the input file * must have a header",
    "Make sure the first elements of the first two lines are of different lengths",
    "Error: files * and * don't have the same header. Input files must have the same header.",
    "Warning: 4 different lines with the same research key were identified",
    "File comparison may not work correctly. Here are your options:",
    "c (TEST_PROMPT_DK = True)",
    "List of key duplicates written in file",
    "run_dq job initialised. Input files * and * are going to be sorted and compared.",
    "lines read in * ms. * lines read in total.",
    "lines read in * ms. * lines read in total and * lines written in the output file.",
    "Maximum number of lines reached (* lines) for list no. 1, sorting...",
    "Current list sorted. Generating temporary file no. 1...",
    "Temporary file successfully generated, input file reading goes on...",
    "Filling buffer array - Iteration no. *",
    "Emptying buffer array in output file (and removing dupes)...",
    "Deleting temporary file no. 2",
    "Output file * successfully generated (25 lines written, 4 pure duplicates removed).",
    "Examples of duplicates (limited to *):",
    "Input file has more than * lines. It will be split in * files (max file nb set to *). Continue? (y/n)",
    "y (TEST_PROMPT_SPLIT = True)",
    "Splitted file no. 1 (*) successfully generated",
    "Test dq No. 1",
    "Test dq No. 2",
    "Test dq No. 3",
    "[dq] run_dq: start",
    "[dq] sort_file: start (*)",
    "[dq] sort_file: end (* ms)",
    "[dq] compare_files: start",
    "[dq] compare_files: end (* ms)",
    "[dq] run_dq: end (* ms)",
    "[dq] file_match: start",
    "Comparison result available here",
    "[dq] file_match: end",
    "[toolSplit] split_file: start",
    "[toolSplit] split_file: end",
]
