SELECT edf.PRM
, TO_CHAR(edf.PS) PS_EDF, TO_CHAR(sge.PS) PS_ENEDIS
, TO_CHAR(sge.INT_REGLAGE_DJ) INT_REGLAGE_DJ
, sge.CALIBRE_DJ CALIBRE_DJ_TXT
, sge.ETAT_CONTRACTUEL
, sge.CONTRAT
, sge.COMPTEUR
, sge.DATE_DER_MES, sge.DATE_DER_CHGT_FRN, sge.DATE_DER_MODIF_FTA
FROM EDF edf
JOIN SGE sge ON edf.PRM = sge.PRM
WHERE edf.PS <> sge.PS