SELECT POINT FROM
(
	SELECT DISTINCT seg.PRM_ID as POINT, srv.ETAT_CODE, srv.DATE_DEBUT, srv.DATE_FIN, srv.MOTIF_FIN_LIBELLE
	, DENSE_RANK() OVER (PARTITION BY seg.PRM_ID ORDER BY srv.DATE_DEBUT DESC, srv.DATE_MODIFICATION DESC) as RANG
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	WHERE 1=1
	AND SERVICE_TYPE = 'OPPENR'
	AND srv.ETAT_CODE IN ('ACTIF', 'DEMANDE')
	AND seg.SEGMENT = 'C5'
	--AND seg.PRM_ID = '05194645430929'
)
WHERE RANG = '1'