SELECT POINT, ETAT FROM
(
	SELECT seg.PRM_ID POINT
	, srv.SERVICE_ID ID
	, srv.SERVICE_TYPE TYPE
	, srv.ETAT_CODE ETAT
	, srv.DATE_DEBUT
	, DENSE_RANK() OVER (PARTITION BY seg.PRM_ID ORDER BY srv.SERVICE_TYPE DESC, srv.ETAT_CODE, srv.DATE_DEBUT DESC, srv.SERVICE_ID DESC) as RANG
	FROM ADA_SCH.SERVICE_SOUSCRIT srv
	LEFT JOIN ADA_SCH.PRM_SEGMENT seg ON srv.PRM_SEGMENT_ID = seg.ID
	LEFT JOIN ADA_SCH.MESURE mes ON srv.MESURE_ID = mes.ID
	WHERE 1=1
	AND srv.ETAT_CODE IN ('ACTIF', 'DEMANDE')
	AND seg.SEGMENT = 'C5'
	AND srv.SERVICE_TYPE = 'TRANSREC'
	AND mes.TYPE_CODE = 'IDX'
	--AND seg.PRM_ID LIKE '211%'
	--AND seg.PRM_ID = '21100289408993'
)
WHERE RANG = 1