CL = [
    "Log file initialised",
    "Python version:",
    "Test gmail - KO, recipients not configureed",
    "Mail folder 'mails/' successfully initialised",
    "Test gmail - [Test] Python mail - var dict, HTML template with attachments",
    "Test gmail - [Test] Python mail - var dict, Python template with recipients",
    "Test gmail - [Test] Python mail - no var dict, HTML template",
    "Test gmail - [Test] Python mail - no var dict, Python template",
    "Template variables have been replaced",
    "Test no_auth",
    "Test outlook",
    "Warning: * is not an internal email address. Send anyways?*",
    "Getting recipients from",
    "HTML template * successfully loaded",
    "Skipped sending (TEST = True)",
    "Sending mail 'test' to",
    "Paul ARNAUD (IN) <paularnaud2@gmail.com>",
    "Paul ARNAUD (FILE) <paularnaud2@gmail.com>",
    "Mail saved to",
    "Checking if all recipients are internal",
    "is not an internal email address",
    "y (TEST = True)",
    "getaddrinfo failed",
    "2147221005",
    "'dear tester' and 'HTML template case' found in last_sent",
    "'dear tester' and 'Python template case' found in last_sent",
    "'@@NAME@@' and 'HTML template case' found in last_sent",
    "'@@NAME@@' and 'Python template case' found in last_sent",
    "[ttry] Exception caught match expected ('[Errno 11001] getaddrinfo failed')",
    "[ttry] Exception caught match expected ('2147221005')",
    "Password decrypted: 'my_password'",
]
